#pragma once

#define IOCTL_DEVMON_ADD_DEVICE CTL_CODE(0x8000, 0x800, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_DEVMON_REMOVE_DEVICE CTL_CODE(0x8000, 0x801, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_DEVMON_REMOVE_ALL_DEVICE CTL_CODE(0x8000, 0x802, METHOD_NEITHER, FILE_ANY_ACCESS)
